<?php
$items = $block->getDataBlocks();
$slidesToShow = $block->getData('slidetoshow');
$slidesToScroll = $block->getData('slidetoscroll');
$checkSlide = $block->getSlideBlogManager();
$numberInPage = $block->getBlogInPage();
$numberInSilde = $block->getBlogInSlide();
?>
<div class="products wrapper grid products-grid">
    <ol class="products list items product-items <?php if($checkSlide==1) echo "my-list"; ?>">
        <?php $dem=0; foreach($items as $item):  ?>
            <?php if($dem == $numberInPage) break; $dem++; ?>
            <?php $imagePath = $block->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'blog/index/' . $item['images'];
            ?>
            <li class="item product product-item">
                <div class="product-item-info" style="width: 70%" data-container="product-grid">
                    <a href="<?php echo $block->getUrl('blog/index/detail').'id/'.$item['id']; ?>" class="product photo product-item-photo"
                       tabindex="-1">
                        <span class="product-image-container" style="width:240px;">
                            <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                <img class="product-image-photo"
                                     src="<?php echo $imagePath  ?>"
                                     max-width="240" max-height="300" alt="Name of product"></span>
                            </span>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?php echo $block->getUrl('blog/index/detail').'id/'.$item['id']; ?>">
                                <?php echo $item['title'] ?> </a>
                        </strong>
                        <div class="price-box price-final_price" data-role="priceBox" data-product-id="436"
                             data-price-box="product-id-436"><span class="normal-price">
                                    <span class="price-container price-final_price tax weee">
                                        <span class="price-label"><?php echo $item['description'] ?> </span>
                                    </span>
                                </span>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".my-list").slick({
                dots: true,
                infinite: true,
                speed: 300,
                slidesToShow: <?php echo $numberInSilde; ?>,
                slidesToScroll: 4,
                autoplay: true,
                autoplaySpeed: 2000,
                arrows: true,
                responsive: [
                    {
                        breakpoint: 1205,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 3,
                            infinite: true,
                            arrows: false,
                            dots: true
                        }
                    },
                    {
                        breakpoint: 780,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 3,
                            rows: 2,
                            infinite: true,
                            arrows: false,
                            dots: false
                        }
                    },
                    {
                        breakpoint: 640,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 3,
                            rows: 2,
                            infinite: true,
                            arrows: false,
                            dots: false
                        }
                    },
                ]
            });
        });
    });
</script>
